{"uuid": "19ba7784-0105-4ad1-a13c-09262cbe4304", "children": ["738122d8-c10f-4ea6-844c-4262530a43de"], "befores": [{"name": "get_driver", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip\n", "trace": "  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PyTest-Automation-Framework-master\\tests\\conftest.py\", line 35, in get_driver\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\webdriver_manager\\chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\webdriver_manager\\core\\download_manager.py\", line 28, in download_file\n    response = self._http_client.get(url)\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\webdriver_manager\\core\\http.py\", line 33, in get\n    self.validate_response(resp)\n  File \"C:\\Users\\vaishnavi.gopala\\Pepsico\\Pepsico-CV_QA_Automation\\venv\\lib\\site-packages\\webdriver_manager\\core\\http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n"}, "start": 1690966455385, "stop": 1690966463949}], "start": 1690966455385, "stop": 1690966464025}